import './globals.css'

export const metadata = {
    title: 'Teodor | Portfolio',
    description: 'Generated by create next app',
    icon: '/logo.png'
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>{children}</body>
        </html>
    )
}
